[theme]
primaryColor = "#4682B4"  # Steel Blue
backgroundColor = "#F5F5F5"  # Light Grey
secondaryBackgroundColor = "#FFFFFF"  # White
textColor = "#333333"  # Dark Grey
font = "serif"  # Default font
